# Generated by Django 4.1.9 on 2024-10-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='past_values',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text1', models.IntegerField()),
                ('text2', models.IntegerField()),
                ('val', models.IntegerField()),
            ],
        ),
    ]
